feat(desktop): support local react devtools
netless-io/flat pull request #1084
Opened 2021-11-11 03:41 UTC by Matrixbirds

2021-11-11 03:44 UTC, hyrious approved these changes, later dismissed

2021-11-11 05:21 UTC, BlackHole1 requested changes

2021-11-11 05:21 UTC, BlackHole1 commented on desktop/main-app/src/window-manager/window-main/index.ts
> +import path = require("path");
```suggestion
import path from "path";
```

2021-11-11 05:21 UTC, BlackHole1 commented on desktop/main-app/src/window-manager/window-main/index.ts
> +    private injectExtensions(win: CustomWindow, extensionName: string): void {
```suggestion
    private static loadExtension(win: CustomWindow, extensionName: "react-devtools"): void {
```

2021-11-11 05:21 UTC, BlackHole1 commented on desktop/main-app/src/window-manager/window-main/index.ts
> +        );
```suggestion
        const extPath = path.resolve(__dirname, "..", "..", "..", "..", "..", "third_party", "extensions", extensionName);
```

2021-11-12 09:40 UTC, hyrious approved these changes

2021-11-16 11:52 UTC, BlackHole1 approved these changes

2021-11-16 11:53 UTC, merged

2021-11-17 03:53 UTC, LitoMore commented
> As many research, I found the root cause. @Matrixbirds 

What it is?

2021-11-17 03:55 UTC, BlackHole1 commented
> > As many research, I found the root cause. @Matrixbirds
> 
> What it is?

see: https://github.com/MarshallOfSound/electron-devtools-installer/issues/205

2021-11-17 03:59 UTC, BlackHole1 commented
Let me answer for him.

If your computer has developed other electron projects before, they also used `electron-devtools-installer` to load the `react devtools`, but their `react devtools` are very old and cause flat to report an error on startup. This is because the version of `react-refresh` we are using is not compatible with older versions of `react devtools`

2021-11-17 04:01 UTC, LitoMore commented
Can we use a forked package instead of storing those files to code base?

2021-11-17 04:04 UTC, BlackHole1 commented
> Let me answer for him.
> 
> If your computer has developed other electron projects before, they also used `electron-devtools-installer` to load the `react devtools`, but their `react devtools` are very old and cause flat to report an error on startup. This is because the version of `react-refresh` we are using is not compatible with older versions of `react devtools`
> 
> So we discussed and decided to maintain the react devtools in a separate flat project.

The benefits of this are
1. no need to worry about the installation of `react devtools` failing in China (network problems)
2. no need to worry about conflicts with other projects' react-devtools
3. Instead of waiting for electron-devtools-installer to fix it, or electron to fix it, we can always patch it. For more information on this see: https://github.com/netless-io/flat/issues/1031#issuecomment-949212608

2021-11-17 04:06 UTC, BlackHole1 commented
> Can we use a forked package instead of storing those files to code base?

This is difficult, I'm afraid, because the files are actually obtained from the crx decompression.
see: https://github.com/MarshallOfSound/electron-devtools-installer/blob/65ffa894bf635745d9399e79fb38682ccfd9c6e0/src/downloadChromeExtension.ts#L26-L32

2021-11-17 04:44 UTC, LitoMore commented
> no need to worry about the installation of react devtools failing in China (network problems)

This should not be called benefit. Developers should be able to solve network issues. We don't have to care network issue for them. Like #1037 does.

It is not elegant to store these unreadable files directly in the project. I think we can use `git submodule` or store these files in a new npm package.

The main point is: we don't need to track these files in the current repo.

We can use npm or GitHub repo (prefered) for storing this:

> What is `netless/electron-devtools-installer`: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository

```diff
"devDependencies": {
+	"netless/electron-devtools-installer": "0.0.1"
}
```

In `desktop/main-app/src/window-manager/window-main/index.ts`:

```diff
const extPath = path.resolve(
	__dirname,
	"..",
	"..",
	"..",
	"..",
	"..",
-	"third_party",
+	"node_modules",
+	"electron-devtools-installer",
```

2021-11-17 05:28 UTC, BlackHole1 commented
you've got a point. I'm not going to use the git submodule approach to do this, as it's a bit of a pain to manage.

npm is a good idea

2021-11-17 06:04 UTC, Cyberhan123 commented
> you've got a point. I'm not going to use the git submodule approach to do this, as it's a bit of a pain to manage.
> 
> npm is a good idea

@LitoMore 
yes, git submodule not a good idea in many common

1. You must use `git submodule update` before `git commit -a`
2. The  `git submodule update` not in right  branch (‘detached HEAD’ state) so ,must check out branch into `master` or anyothers
3. Not friendly for github or gitlab to manage PR

2021-11-17 06:27 UTC, LitoMore commented
The GitHub repo what I mean is used for the npm package. It's easier for bumping versions and we don't have to publish any package to npm.