add eslint rule
netless-io/flat pull request #1129
Opened 2021-11-23 09:58 UTC by syt-honey

1. add `object-curly-newline` rule
2.  turn off `comma-dangle` rule
3. format main dir

2021-11-23 10:04 UTC, BlackHole1 requested changes

2021-11-23 10:04 UTC, BlackHole1 commented on desktop/main-app/package.json
> +    "fix": "eslint --fix 'src/**/*.{ts, tsx}' 'typings/*.ts'",
remove

2021-11-23 10:04 UTC, BlackHole1 commented on desktop/renderer-app/package.json
> +    "fix": "eslint --fix 'src/**/*.{ts, tsx}' 'typings/*.ts'"
remove

2021-11-23 10:04 UTC, BlackHole1 commented on packages/flat-components/package.json
> +    "fix": "eslint --fix 'src/**/*.{ts, tsx}' 'typings/*.ts'",
remove

2021-11-23 10:04 UTC, BlackHole1 commented on web/flat-web/package.json
> +    "fix": "eslint --fix 'src/**/*.{ts, tsx}' 'typings/*.ts'"
remove

2021-11-23 10:04 UTC, BlackHole1 commented on yarn.lock
>    dependencies:
reset `yarn.lock`

2021-11-23 10:06 UTC, BlackHole1 commented
we don't need `fix script`.

you should reset `yarn.lock` file change, because `package.json` no any update

2021-11-23 10:23 UTC, syt-honey commented
> we don't need `fix script`.
> 
> you should reset `yarn.lock` file change, because `package.json` no any update

done.

2021-11-23 10:33 UTC, BlackHole1 commented
@syt-honey CI has failed, can you look at it?

2021-11-24 02:08 UTC, BlackHole1 commented
`object-curly-newline` unable to meet demand

2021-11-24 02:08 UTC, closed without merging