refactor(classroom): simplify the flow of the create room
netless-io/flat pull request #1222
Opened 2021-12-17 10:16 UTC by Cheerego7

- refactor(flat-components): adjust style of RecordButton components
- chore(flat-components): adjust text of i18n and type of the HeroButton component

2021-12-17 10:16 UTC, hyrious submitted a review, later dismissed

2021-12-17 10:22 UTC, BlackHole1 commented
I will review code at late

2021-12-17 15:06 UTC, BlackHole1 requested changes

2021-12-17 15:06 UTC, BlackHole1 commented on packages/flat-components/src/components/HomePage/HomePageHeroButton/index.tsx
> +import beginSVG from "./icons/begin.svg";
forget https://github.com/netless-io/flat/blob/46d0bf07d6cfbc51acc1f295a62234d17cb5181b/web/flat-web/src/pages/HomePage/MainRoomMenu/CreateRoomBox.tsx#L1

2021-12-20 02:42 UTC, Cheerego7 commented on packages/flat-components/src/components/HomePage/HomePageHeroButton/index.tsx
> +import beginSVG from "./icons/begin.svg";
keep unchanged

2021-12-20 03:12 UTC, BlackHole1 approved these changes

2021-12-20 03:37 UTC, merged