feat(ui): add ClassRoom Timer
netless-io/flat pull request #1288
Opened 2022-01-12 09:25 UTC by Matrixbirds

1. Add `Timer` to `flat-components`.
2. Add `Timer` to `renderer-app` and `flat-web`.

2022-01-12 10:07 UTC, BlackHole1 requested changes
`Countdown` => `Timer`

2022-01-12 10:07 UTC, BlackHole1 commented on desktop/renderer-app/src/pages/BigClassPage/index.tsx
> +                ) : classRoomStore.roomInfo?.beginTime && <Countdown state={classRoomStore.roomStatus !== RoomStatus.Started ? 'paused' : 'started'} beginTime={classRoomStore.roomInfo.beginTime} />}
`<Countdown roomStatus={classRoomStore.roomStatus}`

2022-01-12 10:07 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Countdown/index.tsx
> +}
use data-fns function

```suggestion
const prefixInteger = (number: number): string => {
    return String(number).padStart(2, "0");
}

const renderTime = (seconds: number): string => {
    const { hours, minutes, seconds } = intervalToDuration({start: 0, end: seconds * 1000});

    return `${prefixInteger(hours)}:${prefixInteger(minutes)}:${prefixInteger(seconds)}`
}
```

2022-01-12 10:07 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Countdown/index.tsx
> +    state: "paused" | "started";
```suggestion
    state: RoomStatus
```

2022-01-12 10:07 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Countdown/index.tsx
> +};
use `useIsUnMounted`

see: https://github.com/netless-io/flat/blob/3edb21b682cebc62c45cc60d60d544d92e6afa70/desktop/renderer-app/src/utils/hooks/lifecycle.ts#L4-L13

2022-01-13 03:15 UTC, BlackHole1 requested changes

2022-01-13 03:15 UTC, BlackHole1 commented on desktop/renderer-app/src/components/AppStoreButton/index.tsx
> +    Timer: countdownSVG,
```suggestion
    Timer: timerSVG,
```

2022-01-13 03:15 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +            <span>{format(timestamp, "mm:ss")}</span>
forget `hh`?

2022-01-13 03:15 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    const roomStatusCls = classnames(`countdown-${roomStatus}`);
```suggestion
    const roomStatusCls = classnames(`timer-${roomStatus}`);
```

2022-01-13 03:15 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +        <span className="countdown-bar">
```suggestion
        <span className="timer-bar">
```

2022-01-13 03:15 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/style.less
> +.countdown-bar {
```suggestion
.timer-bar {
```

2022-01-13 03:27 UTC, LitoMore requested changes

2022-01-13 03:27 UTC, LitoMore commented on desktop/renderer-app/src/pages/BigClassPage/index.tsx
> +                    )
FYI: https://eslint.org/docs/rules/no-negated-condition

I will add this rule to our project later.

```suggestion
                {classRoomStore.isCreator ? (
                    classRoomStore.roomInfo?.beginTime && (
                        <Timer
                            roomStatus={classRoomStore.roomStatus}
                            beginTime={classRoomStore.roomInfo.beginTime}
                        />
                    )
                ) : (
                    <RoomInfo
                        roomStatus={classRoomStore.roomStatus}
                        roomType={classRoomStore.roomInfo?.roomType}
                    />
```

2022-01-13 03:27 UTC, LitoMore commented on desktop/renderer-app/src/pages/OneToOnePage/index.tsx
> +                    )
Ditto.

2022-01-13 03:27 UTC, LitoMore commented on desktop/renderer-app/src/pages/SmallClassPage/index.tsx
> +                    )
Ditto.

2022-01-13 03:27 UTC, LitoMore commented on web/flat-web/src/pages/BigClassPage/index.tsx
> +                    )
Ditto.

2022-01-13 03:27 UTC, LitoMore commented on web/flat-web/src/pages/OneToOnePage/index.tsx
> +                    )
Ditto.

2022-01-13 03:27 UTC, LitoMore commented on web/flat-web/src/pages/SmallClassPage/index.tsx
> +                    )
Ditto.

2022-01-13 08:21 UTC, Matrixbirds commented on desktop/renderer-app/src/pages/BigClassPage/index.tsx
> +                    )
Sure. Glad to see your config.

2022-01-13 08:24 UTC, hyrious approved these changes, later dismissed

2022-01-14 08:21 UTC, BlackHole1 requested changes

2022-01-14 08:21 UTC, BlackHole1 commented on web/flat-web/src/components/AppStoreButton/index.tsx
> +    Timer: countdownSVG,
```suggestion
    Timer: timerSVG,
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +import { intervalToDuration } from "date-fns/esm";
```suggestion
import { intervalToDuration } from "date-fns/fp";
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    return String(number).padStart(2, "0");
```suggestion
    return number === undefined ? "00" : String(number).padStart(2, "0");
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    };
```suggestion
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +            updateTime(args.current);
```suggestion
            if (state === RoomStatus.Started) {
                updateTimestamp(Date.now());
            }
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    return intervalToDuration({ start: beginTime, end: timestamp });
```suggestion
    return intervalToDuration({
        start: beginTime,
        end: timestamp,
    });
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    const roomStatusCls = classnames(`timer-${roomStatus}`);
```suggestion
```

2022-01-14 08:21 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +            <span className={roomStatusCls}>{t("room-started")}</span>
```suggestion
            <span className={`timer-${roomStatus}`}>{t("room-started")}</span>
```

2022-01-14 08:37 UTC, BlackHole1 requested changes

2022-01-14 08:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +        : `${paddingZero(minutes)}:${paddingZero(seconds)}`;
```suggestion
    return hours > 0
        ? `${paddingZero(hours!)}:${paddingZero(minutes!)}:${paddingZero(seconds!)}`
        : `${paddingZero(minutes!)}:${paddingZero(seconds!)}`;
```

`hours` / `minutes` / `seconds`  must be `number`. see: https://github.com/date-fns/date-fns/blob/54ec0a5e5ca3f472085d3b56be30d801b90829ac/src/intervalToDuration/index.ts#L38

this is `date-fns` bug

2022-01-14 08:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +const paddingZero = (number?: number): string => {
```suggestion
const paddingZero = (number: number): string => {
```

2022-01-14 08:45 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +        : `${paddingZero(minutes)}:${paddingZero(seconds)}`;
see: https://github.com/date-fns/date-fns/pull/2917

2022-01-14 17:28 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +        : `${paddingZero(minutes)}:${paddingZero(seconds)}`;
https://github.com/date-fns/date-fns/issues/2891#issuecomment-1003070337

2022-01-17 08:16 UTC, BlackHole1 requested changes

2022-01-17 08:16 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +export type TimerDuration = Required<Duration>;
```suggestion
export type TimerDuration = Omit<Required<Duration>, "weeks">;
```

2022-01-17 08:16 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +};
```suggestion
    const minutesAndSeconds = `${paddingZero(minutes)}:${paddingZero(seconds)};

    return hours > 0 ? `${paddingZero(hours)}:${minutesAndSeconds}` : minutesAndSeconds;
};
```

2022-01-17 09:12 UTC, BlackHole1 requested changes

2022-01-17 09:12 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    const minutesAndSeconds = `${paddingZero(minutes)}:${paddingZero(seconds)};
```suggestion
    const minutesAndSeconds = `${paddingZero(minutes)}:${paddingZero(seconds)}`;
```

2022-01-17 09:41 UTC, Cheerego7 commented on web/flat-web/src/pages/SmallClassPage/index.tsx
> +const a = "";
what's this?

2022-01-17 09:41 UTC, BlackHole1 requested changes

2022-01-17 09:41 UTC, BlackHole1 commented on desktop/renderer-app/src/components/AppStoreButton/index.tsx
> +import countdownSVG from "../../assets/image/countdonw.svg";
```suggestion
import countdownSVG from "../../assets/image/countdown.svg";
```

2022-01-17 09:43 UTC, BlackHole1 commented on web/flat-web/src/pages/SmallClassPage/index.tsx
> +const a = "";
this is test code

2022-01-17 09:52 UTC, Cheerego7 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +    const state = useRef<typeof roomStatus>(roomStatus);
`state` -> `roomState`

2022-01-17 10:39 UTC, Cheerego7 commented on packages/flat-components/src/components/ClassroomPage/Timer/index.tsx
> +import "./style.less";
placed at the top, and add a newline

2022-01-17 11:09 UTC, BlackHole1 approved these changes

2022-01-17 11:10 UTC, BlackHole1 commented
please re-review

cc: @LitoMore

2022-01-17 11:12 UTC, Cheerego7 approved these changes

2022-01-17 11:44 UTC, LitoMore approved these changes

2022-01-17 11:44 UTC, LitoMore approved these changes

2022-01-17 11:45 UTC, merged