feat(web,electron,component): add agora sso
netless-io/flat pull request #1341
Opened 2022-01-27 07:30 UTC by Matrixbirds

2022-01-27 08:32 UTC, BlackHole1 requested changes

2022-01-27 08:32 UTC, BlackHole1 commented on desktop/renderer-app/src/pages/LoginPage/index.tsx
> +        [agreementChecked],
```suggestion
        [agreementChecked, message],
```

2022-01-27 08:32 UTC, BlackHole1 commented on packages/flat-components/src/components/LoginPage/LoginContent/LoginContent.stories.tsx
> +                handleClickAgreement={handleClickAgreement}
```suggestion
                handleClickAgreement={() => updateAgreement(!agreement)}
```

2022-01-27 08:32 UTC, BlackHole1 commented on packages/flat-components/src/components/LoginPage/LoginContent/LoginContent.stories.tsx
> +    };
```suggestion
```

2022-01-27 08:32 UTC, BlackHole1 commented on packages/flat-components/src/components/LoginPage/LoginPanel.stories.tsx
> +            }
```suggestion
            if (!agreement) {
                void message.info(i18n.t("agree-terms"));
                return;
            }
            
            switch (loginChannel) {
                case "wechat": {
                    setWeChatLogin(true);
                    break;
                }
                case "github": {
                    Modal.info("need i18n");
                    break;
                }
                default: {
                    break;
                }
            }
```

2022-01-27 08:32 UTC, BlackHole1 commented on web/flat-web/src/pages/LoginPage/index.tsx
> +                    }
```suggestion
                    if (!roomUUID) {
                        pushHistory(RouteNameType.HomePage);
                        return;
                    }
                    
                    if (globalStore.isTurnOffDeviceTest) {
                        await joinRoomHandler(roomUUID, pushHistory);
                    } else {
                        pushHistory(RouteNameType.DevicesTestPage, {
                            roomUUID
                        });
                    }
```

2022-01-27 08:32 UTC, BlackHole1 commented on web/flat-web/src/pages/LoginPage/index.tsx
> +        [agreement],
```suggestion
        [agreement, message],
```

2022-01-27 08:32 UTC, BlackHole1 commented on web/flat-web/src/pages/LoginPage/index.tsx
> +                    />
```suggestion
```

2022-01-27 08:32 UTC, BlackHole1 commented on web/flat-web/src/utils/routes.ts
> +export function useURLParams(): Record<string, any> {
react-router hook?

2022-01-27 09:13 UTC, Cheerego7 commented on packages/flat-components/src/components/LoginPage/index.less
> +}
add newline

2022-01-27 09:14 UTC, Cheerego7 commented on packages/flat-components/src/components/LoginPage/LoginButton/index.less
> +}
add newline

2022-01-27 10:44 UTC, Cheerego7 approved these changes, later dismissed

2022-01-28 01:11 UTC, Matrixbirds commented
cc @BlackHole1

2022-01-28 01:12 UTC, Matrixbirds commented
@BlackHole1  any progress?

2022-01-28 02:42 UTC, BlackHole1 approved these changes

2022-01-28 03:00 UTC, merged