chore(project): migrate to pnpm
netless-io/flat pull request #1442
Opened 2022-03-25 08:31 UTC by hyrious

2022-03-25 08:59 UTC, crimx submitted a review, later dismissed

2022-03-28 02:40 UTC, BlackHole1 requested changes

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/check-code.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/deploy-storybook.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/deploy-web-dev-cn.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/deploy-web-dev-us.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/deploy-web-prod-cn.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on .github/workflows/deploy-web-prod-us.yml
> +      - uses: pnpm/action-setup@v2.0.1
```suggestion
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
```

2022-03-28 02:40 UTC, BlackHole1 commented on scripts/init-agora-configure/configure-agora-sdk.js
> +    // npmrcOptions["node-linker"] = "hoisted";
@crimx

2022-03-28 02:56 UTC, BlackHole1 requested changes
forget changes:
* https://github.com/netless-io/flat/blob/main/scripts/ci/install-changed-package-dependencies.js
* https://github.com/netless-io/flat/blob/main/scripts/ci/remove-workspace-packages.js

2022-03-28 02:56 UTC, BlackHole1 commented on cspell.config.js
> +        "pnpm-lock.yaml",
```suggestion
        "cspell.config.js",
        "pnpm-lock.yaml",
```

2022-03-28 02:56 UTC, BlackHole1 commented on desktop/renderer-app/vite.config.ts
>          copy({
fix `vite-plugin-eslint` in renderer-app

2022-03-28 02:56 UTC, BlackHole1 commented on package.json
> +    "lint": "lint-staged && pnpm -r --workspace-concurrency 1 lint",
improve lint script

2022-03-30 09:08 UTC, BlackHole1 commented
ready merge

2022-03-31 02:02 UTC, BlackHole1 approved these changes

2022-03-31 02:02 UTC, merged