feat(project): support loading more cloudStorage data
netless-io/flat pull request #1443
Opened 2022-03-25 09:17 UTC by Cheerego7

2022-03-25 09:21 UTC, hyrious approved these changes, later dismissed

2022-03-25 09:23 UTC, BlackHole1 approved these changes, later dismissed

2022-03-25 10:24 UTC, crimx requested changes

2022-03-25 10:24 UTC, crimx commented on packages/flat-components/src/components/FlatIcons/icons/SVGListLoading.tsx
> +import "../style.less";
Also add the new icon to storybook

2022-03-25 10:24 UTC, crimx commented on packages/flat-components/src/containers/CloudStorageContainer/index.tsx
> +                    await store.fetchMoreCloudStorageData(page);
use `safePromise`

2022-03-25 10:24 UTC, crimx commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +        const { files: cloudFiles } = await listFiles({
Maintain a fetching state so that subsequent requests can be ignored during fetching state

2022-03-25 10:24 UTC, crimx commented on packages/flat-components/src/containers/CloudStorageContainer/index.tsx
> +                setCloudStorageDataPagination(cloudStorageDataPagination + 1);
Pagination should be undated only after a success fetching?

2022-03-25 10:24 UTC, crimx commented on packages/flat-components/src/containers/CloudStorageContainer/store.ts
> +        return this.files.length;
`this.filesMap.size`

2022-03-29 05:48 UTC, crimx requested changes

2022-03-29 05:48 UTC, crimx commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +    public isFetchingMoreData = false;
`isFetchingFiles` or `isFetchingFileList`

2022-03-29 05:48 UTC, crimx commented on packages/flat-components/src/containers/CloudStorageContainer/index.tsx
> +            const fetchMoreCloudStorageData = async (page: number): Promise<void> => {
No need to wrap this function anymore.

2022-03-29 05:48 UTC, crimx commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +            isFetchingMoreData: false,
should observable

2022-03-29 05:48 UTC, crimx commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +    public fetchMoreCloudStorageData = async (page: number): Promise<void> => {
skip if fetching

2022-03-29 06:57 UTC, crimx approved these changes

2022-03-29 07:00 UTC, hyrious approved these changes

2022-03-29 07:08 UTC, merged