fix(storybook): add mock data to the cloudStorageContainer component
netless-io/flat pull request #1460
Opened 2022-03-31 10:07 UTC by Cheerego7

2022-03-31 10:10 UTC, BlackHole1 requested changes

2022-03-31 10:10 UTC, BlackHole1 commented on packages/flat-components/src/containers/CloudStorageContainer/CloudStorageContainer.stories.tsx
> +                        fileSize: file.fileSize,
nit:
```suggestion
                for (const { fileName, fileSize } of newFilesData) {
                    this.files.push({
                        fileUUID: faker.datatype.uuid(),
                        fileName,
                        fileSize,
```

2022-03-31 10:10 UTC, BlackHole1 commented on packages/flat-components/src/containers/CloudStorageContainer/CloudStorageContainer.stories.tsx
> +                );
```suggestion
                console.warn("the cloud storage files is enough");
                return Promise.resolve();
```

2022-04-01 08:28 UTC, crimx approved these changes

2022-04-01 08:29 UTC, BlackHole1 approved these changes

2022-04-01 08:29 UTC, merged