refactor: adjust the HotKeySetting page layout
netless-io/flat pull request #157
Opened 2021-01-28 10:12 UTC by syt-honey

adjust the HotKeySetting page layout

2021-01-28 10:26 UTC, crimx requested changes
Thanks for PR! 谢谢你的 PR! ❤️ 有几处需要修改。有什么问题多交流。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableKeys = ["tools", "edit"];
固定的变量请移出组件，以免组件重新渲染时反复生成。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableTitleList = [
固定的变量请移出组件，以免组件重新渲染时反复生成。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableExpandRow = {
固定的变量请移出组件，以免组件重新渲染时反复生成。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const tableRow = (): any => {
只有特殊的情况下才能用 `any` 。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +        const tableData: any = [];
只有特殊的情况下才能用 `any` 。下面的 `any` 同上。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +            tableData.push(item);
可以改成 

```js
tableData.push({
  name: data;
  key: index;
  desc: HotKeyTableRow[index];
});
```

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +                row.key = `${row.name + index}`;
不建议直接修改属性。

2021-01-28 10:26 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +        return HotKeyTableExpandTitleList;
直接使用 `HotKeyTableExpandTitleList` 既可。不需要包一个函数。

2021-01-28 10:28 UTC, BlackHole1 requested changes

2021-01-28 10:28 UTC, BlackHole1 commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    };
```typescipt
return HotKeyTableKeys.map((data: HotKeyTable, index) => {
    return {
        name: data,
        key: index,
        desc: HotKeyTableRow[index]
    }
});

interface HotKeyTable {
    name: string;
    key: number;
    desc: string;
}
```

2021-01-28 10:32 UTC, BlackHole1 requested changes

2021-01-28 10:32 UTC, BlackHole1 commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +        return HotKeyTableTitleList;
这里没有做任何的处理，是否可以直接使用: HotKeyTableTitleList

2021-01-28 10:32 UTC, BlackHole1 commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableExpandTitleList = [
如果对象不变的情况的下，建议使用: `Object.freeze`

2021-01-28 10:32 UTC, BlackHole1 commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableTitleList = [
同时使用: `Object.freeze`

2021-01-29 03:52 UTC, syt-honey commented
> Thanks for PR! 谢谢你的 PR! ❤️ 有几处需要修改。有什么问题多交流。

Jack 前辈你好，我按照你和 BlackHole 前辈的指导改了几处并且重新提交了代码，希望你们有空的时候能够帮我看看。

我还有一个疑问想要请教一下：

1. 建议中有一点是 ”不建议直接修改属性。“这里我不是特别明白。我这里的逻辑其实只是想要动态的为扩展子 table 的每行（`HotKeyTableExpandRow`）添加唯一 key。目前我改了一种写法，但是仍然是你说的 “直接修改属性”。如果这样的实现方式不太行，那对于动态添加 key 还有更好的方法吗？

我之前没有接触过 React 和 TS，如果有啥低级问题希望能帮我指出～ 再次感谢你和 BlackHole 前辈 ❤️

2021-01-29 04:00 UTC, crimx requested changes
感谢你的修改🙏 非常不错！还有几处小问题。

2021-01-29 04:00 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    [HotKeyTableKeys[0]]: [
这里可以换个思路，先把 key 写这里，然后通过 `Object.keys(HotKeyTableExpandRow)` 生成 `HotKeyTableKeys` 数组。

2021-01-29 04:00 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    (function setExpandRowKey(): void {
这里包一层即时执行函数的原因是？

2021-01-29 04:00 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const tableRow = (): HotKeyTable[] => {
这里包一层函数的原因是？

2021-01-29 04:00 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +                <Table columns={ HotKeyTableTitleList } dataSource={ tableRow() } expandable={{ expandedRowRender }} pagination={ false } scroll={{ y: 500 }} />
我们的代码风格不需要加空格。

2021-01-29 04:01 UTC, crimx commented
> 目前我改了一种写法，但是仍然是你说的 “直接修改属性”。如果这样的实现方式不太行，那对于动态添加 key 还有更好的方法吗？

看了一下你新的代码明白你的意图了，这么写没有问题啦！

2021-01-29 04:02 UTC, crimx commented
已修改的问题可以点一下 <kbd>resolve</kbd> 。

2021-01-29 04:14 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    (function setExpandRowKey(): void {
目的是在执行下面的操作前先初始化 key 值。我不希望函数中的代码散落在组件里，所以在外面包了一层函数，然后立即执行。

2021-01-29 04:14 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    (function setExpandRowKey(): void {
你有什么建议吗？

2021-01-29 04:14 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +                <Table columns={ HotKeyTableTitleList } dataSource={ tableRow() } expandable={{ expandedRowRender }} pagination={ false } scroll={{ y: 500 }} />
好的，收到。

2021-01-29 04:15 UTC, syt-honey commented
> 已修改的问题可以点一下 Resolve conversation 。

好的

2021-01-29 04:18 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    };
非常感谢指导！下回我知道怎么设置对应的 Type 了，非常感谢 ❤️

2021-01-29 04:58 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    [HotKeyTableKeys[0]]: [
已提交～

2021-01-29 05:05 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    (function setExpandRowKey(): void {
没事的，直接写就行。模块本身就有作用域，不会泄漏出去。

2021-01-29 05:07 UTC, crimx requested changes

2021-01-29 05:07 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableKeys = Object.freeze(Object.keys(HotKeyTableExpandRow));
这个也移到组件外部。

2021-01-29 05:08 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    [HotKeyTableKeys[0]]: [
好哒

2021-01-29 05:10 UTC, crimx commented
React 的函数组件每次更新都会被调用，所以固定不变的东西都移出去就行，这样就不会被反复创建。

2021-01-29 05:13 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableKeys = Object.freeze(Object.keys(HotKeyTableExpandRow));
那生成 key 是不是也应该移到外面去？在当情况下似乎没有必要每次组件渲染的时候都去生成一下 key？😂

2021-01-29 05:14 UTC, syt-honey commented
> React 的函数组件每次更新都会被调用，所以固定不变的东西都移出去就行，这样就不会被反复创建。
 欧克

2021-01-29 05:15 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const HotKeyTableKeys = Object.freeze(Object.keys(HotKeyTableExpandRow));
对哒～

2021-01-29 05:34 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const tableRow = (): HotKeyTable[] => {
这里这样写是出于习惯。我对啥时候应该包一层函数、啥时候直接用变量有些模糊。尤其是有很多返回值的时候。看着就很像是函数，是吧……于是，我就这么写了……🙍

2021-01-29 05:46 UTC, crimx approved these changes

2021-01-29 05:52 UTC, crimx requested changes

2021-01-29 05:52 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const expandedRowRender = (row: HotKeyTable): React.ReactElement => {
太棒了，这么看现在这个 expandedRowRender 也可以移出去是不是？

2021-01-29 05:52 UTC, crimx commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
>  export const HotKeySetting = (): React.ReactElement => {
这里把组件再包上 `React.memo` 就可以进一步避免不必要更新了。注意需要保留函数名。

```js
export const HotKeySetting = React.memo(function HotKeySetting() {  })
```

2021-01-29 06:43 UTC, syt-honey commented on src/renderer-app/src/pages/UserSettingPanel/HotKeySetting.tsx
> +    const expandedRowRender = (row: HotKeyTable): React.ReactElement => {
emm，你说的非常有道理！但是，咱们这个页面本身就是静态的（目前），那为啥不都放出去呢？🤔

2021-01-29 07:00 UTC, crimx approved these changes

2021-01-29 07:01 UTC, Cheerego7 approved these changes

2021-01-29 07:02 UTC, crimx commented
我这边没问题了，写得很不错！👍

2021-01-29 07:13 UTC, BlackHole1 approved these changes

2021-01-29 07:13 UTC, merged

2021-01-29 07:14 UTC, BlackHole1 commented
感谢你的PR，让这个项目更加完善 🚀