chore(flat-components): fix after being banned the teacher terminal d…
netless-io/flat pull request #1649
Opened 2022-08-20 09:17 UTC by shunyue1320

fix after being banned the teacher terminal does not display send button

before:
`press send buttom can't send message, but press Enter can send message`

<img width="392" alt="image" src="https://user-images.githubusercontent.com/47295879/185738196-598a947b-9667-4011-9a00-3b0d3e5ae338.png">

after:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/47295879/185738256-90993b99-4747-4164-99b7-93c7b56cd79e.png">

2022-08-20 09:32 UTC, LitoMore approved these changes

2022-08-20 16:54 UTC, crimx requested changes
Hi thanks for the PR! Looks good. We'll merge it next week after the `classroom-refactor` branch is merged.

2022-08-21 00:54 UTC, shunyue1320 commented
> Hi thanks for the PR! Looks good. We'll merge it next week after the `classroom-refactor` branch is merged.

thanks ！

2022-08-22 10:48 UTC, crimx approved these changes

2022-08-22 10:49 UTC, merged