add modify periodic room page
netless-io/flat pull request #191
Opened 2021-02-02 04:56 UTC by Cheerego7

- add passing props parameters

- add ModifyPeriodicRoomPage entry

- adjust file location in modifi ordinary room's modules

2021-02-02 10:16 UTC, crimx requested changes

2021-02-02 10:16 UTC, crimx commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/PeriodicRoomForm.tsx
> +const typeName = (type: RoomType): string => {
这个有现成的组件，RoomType

2021-02-02 10:16 UTC, crimx commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/PeriodicRoomForm.tsx
> +        form.setFieldsValue({
在 onValuesChange 中更新 form 值，是否有死循环风险？这里应该通过 getValueFromEvent 等在 form item 中预处理。

2021-02-02 10:16 UTC, crimx commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/PeriodicRoomForm.tsx
> +    const [roomType, setRoomType] = useState(RoomType.BigClass);
这些 states 与 form 里的重复，应去掉以避免混乱，在 form 中统一维护。

2021-02-05 03:46 UTC, BlackHole1 requested changes

2021-02-05 03:46 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/WeekRateSelector.tsx
> +export function getWeekNames(weeks: Week[]): string {
这个有现成的方法的

2021-02-05 03:46 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/WeekRateSelector.tsx
> +export function getWeekName(week: Week): string {
这个有现成的方法的

2021-02-05 03:46 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/renderBeginTimePicker.tsx
> +    function validateBeginTimeDate(): RuleObject {
这些方法我记得jack已经写了，你看下能不能复用下

2021-02-05 03:46 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/renderEndTimePicker.tsx
> +                }
这个方法，我记得jack也写了

2021-02-05 04:27 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/WeekRateSelector.tsx
> +export function getWeekNames(weeks: Week[]): string {
放在下个PR修复

2021-02-05 04:27 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/renderBeginTimePicker.tsx
> +    function validateBeginTimeDate(): RuleObject {
放在下个PR修复

2021-02-05 04:27 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/renderEndTimePicker.tsx
> +                }
放在下个PR修复

2021-02-05 04:27 UTC, BlackHole1 submitted a review, later dismissed

2021-02-05 04:27 UTC, BlackHole1 commented on src/renderer-app/src/pages/ModifyPeriodicRoomPage/WeekRateSelector.tsx
> +export function getWeekName(week: Week): string {
放在下个PR修复

2021-02-05 05:01 UTC, crimx approved these changes

2021-02-05 05:01 UTC, merged