feat: add periodicSubRoom rules
netless-io/flat pull request #338
Opened 2021-02-26 07:10 UTC by Cheerego7

2021-02-26 07:16 UTC, BlackHole1 requested changes

2021-02-26 07:16 UTC, BlackHole1 commented on src/renderer-app/src/components/EditRoomPage/renderBeginTimePicker.tsx
> +                let isPreHours = nextEndTime.getHours() - selectedHour === 1;
const

2021-02-26 07:16 UTC, BlackHole1 commented on src/renderer-app/src/components/EditRoomPage/renderBeginTimePicker.tsx
> +                        let roomDurationCompareTime = MIN_CLASS_DURATION - nextEndTime.getMinutes();
const

2021-02-26 07:16 UTC, BlackHole1 commented on src/renderer-app/src/utils/date/index.ts
> +export const excludeRange = (slice1: number, slice2?: number): number[] =>
加个注释描述下把

2021-02-26 07:16 UTC, BlackHole1 commented on src/renderer-app/src/components/EditRoomPage/renderEndTimePicker.tsx
> +        return excludeRange(59);
59代表什么意思

2021-02-26 07:16 UTC, BlackHole1 commented on src/renderer-app/src/components/EditRoomPage/renderEndTimePicker.tsx
> +        return excludeRange(24);
24代表什么意思，可以抽成常量么

2021-02-26 07:23 UTC, Cheerego7 commented on src/renderer-app/src/components/EditRoomPage/renderEndTimePicker.tsx
> +        return excludeRange(59);
disable掉时间选择器中的分钟数值

2021-02-26 07:23 UTC, Cheerego7 commented on src/renderer-app/src/components/EditRoomPage/renderEndTimePicker.tsx
> +        return excludeRange(24);
disable掉时间选择器中的小时数值

2021-02-26 07:29 UTC, crimx approved these changes

2021-02-26 07:33 UTC, BlackHole1 requested changes

2021-02-26 07:33 UTC, BlackHole1 commented on src/renderer-app/src/utils/date/index.ts
> +export const excludeRange = (slice1: number, slice2?: number): number[] =>
这个放在 date 里有点不符合语义

在 utils 下建个 array.ts，放进去吧

这个方法在lodash里，有一样的方法： https://www.lodashjs.com/docs/lodash.range#_rangestart0-end-step1

用lodash 的方法即可

> 注意： 此方法的第二个参数和你的第二个参数表现行为不一致，需要注意

2021-02-26 07:39 UTC, crimx commented on src/renderer-app/src/utils/date/index.ts
> +export const excludeRange = (slice1: number, slice2?: number): number[] =>
@BlackHole1  这个方法跟 lodash 的 range 是相反的。这个方法不是很常见，其他地方用到不多，先放在这里也行。

2021-02-27 02:17 UTC, BlackHole1 commented on src/renderer-app/src/utils/date/index.ts
> +export const excludeRange = (slice1: number, slice2?: number): number[] =>
好的

2021-02-27 02:17 UTC, BlackHole1 approved these changes

2021-02-27 02:18 UTC, merged