build: show warning if building mac on win32
netless-io/flat pull request #351
Opened 2021-03-03 03:30 UTC by crimx

2021-03-03 03:33 UTC, BlackHole1 requested changes

2021-03-03 03:33 UTC, BlackHole1 commented on src/main-app/scripts/Pack.js
> +switch (buildType) {
改为`switch (procrss.platform)` 逻辑会更加清晰

2021-03-03 03:49 UTC, crimx commented on src/main-app/scripts/Pack.js
> +switch (buildType) {
但是 platform 的判断是根据 buildType 决定需不需要的，如果先判断 platform 那么每个 platform 情况下都要再判断一遍 buildType 的情况。

2021-03-04 06:58 UTC, BlackHole1 approved these changes

2021-03-04 06:58 UTC, merged