feat: add home page hero button
netless-io/flat pull request #418
Opened 2021-03-18 10:54 UTC by hyrious

2021-03-18 11:03 UTC, crimx requested changes

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +        alt: "book room",
schedule room

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +import bookSVG from "../../assets/buttons/book.svg";
schedule

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +import bookSmallSVG from "../../assets/buttons/book-small.svg";
schedule

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +        icon: bookSVG,
schedule

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +        iconSmall: bookSmallSVG,
schedule

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/style.less
> +.home-page-hero-buttons {
上面加空行

2021-03-18 11:03 UTC, crimx commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +import { useMediaQuery } from "react-responsive";
换成纯 css 会不会更简单。 react-responsive 看起来好像有点重👀

2021-03-19 00:54 UTC, hyrious commented on packages/flat-components/src/components/HomePageHeroButton/index.tsx
> +import { useMediaQuery } from "react-responsive";
样式可以 css, 但是需要写代码切换图片和文字 0.0
不用库也要自己写一个 useMediaQuery（虽然不难）

2021-03-19 02:27 UTC, crimx approved these changes

2021-03-19 02:27 UTC, merged