feat cancel upload
netless-io/flat pull request #480
Opened 2021-03-31 10:07 UTC by hyrious

- refactor(cloud-storage): unselect all after delete
- feat(cloud-storage): cancel upload

2021-03-31 10:48 UTC, Cheerego7 requested changes

2021-03-31 10:48 UTC, Cheerego7 commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
>          for (const { status } of this.uploadStatusesMap.values()) {
使用 .some 代码逻辑更直观些

2021-03-31 10:48 UTC, Cheerego7 commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +        this.destroy();
destroy 一般用于销毁所有数据，这里应该抽象出一层逻辑用于清理 timer。复用destroy以后加入新逻辑可能会出现问题

2021-03-31 10:48 UTC, Cheerego7 commented on desktop/renderer-app/src/pages/CloudStoragePage/store.tsx
> +            files: tempFiles.reverse(),
这个在 flat-components 端会以时间排序实现

2021-04-01 03:31 UTC, Cheerego7 approved these changes

2021-04-01 03:43 UTC, crimx approved these changes

2021-04-01 03:43 UTC, merged