add modal
netless-io/flat pull request #52
Opened 2020-12-14 12:03 UTC by alwaysmavs

2020-12-14 12:09 UTC, crimx commented on src/renderer-app/src/components/MainRoomMenu.tsx
> +                    <span className="modal-inner-text">开启麦克风</span>
这里应该使用 label 元素以及其 htmlFor 属性，这样用户点击文字也能勾选。

2020-12-14 12:09 UTC, BlackHole1 requested changes

2020-12-14 12:09 UTC, BlackHole1 commented on src/renderer-app/src/components/MainRoomMenu.tsx
> +const { Option } = Select;
import 后需要有一个空行

2020-12-14 12:09 UTC, BlackHole1 commented on src/renderer-app/src/components/MainRoomMenu.tsx
> +const modalWidth: number = 368;
这个不需要放在当前文件的全局上下文中，可以放在 class 里的static里，如:

```typescript
class ClassName {
    renderJoinModal() {
        console.log(ClassName.modalWidth)
    }
    static get modalWidth(): number {
        return 368;
    }
}
```

2020-12-14 12:10 UTC, crimx approved these changes, later dismissed

2020-12-15 01:54 UTC, crimx approved these changes

2020-12-15 02:01 UTC, BlackHole1 approved these changes

2020-12-15 02:01 UTC, merged