add verify wechat login
netless-io/flat pull request #64
Opened 2020-12-23 08:05 UTC by Cheerego7

- add WeChat avatar to MainPageLayout
- add verify wechat login

2020-12-23 08:10 UTC, BlackHole1 requested changes

2020-12-23 08:10 UTC, BlackHole1 commented on src/renderer-app/src/IndexPage.tsx
> +    isUnmounted: boolean;
前面加上 `private`

2020-12-23 08:10 UTC, BlackHole1 commented on src/renderer-app/src/IndexPage.tsx
> +        this.isUnmounted = false;
`constructor` 可以删除，直接在上面写: `private isUnmounted = false`

2020-12-23 08:10 UTC, BlackHole1 commented on src/renderer-app/src/IndexPage.tsx
> +        setTimeout(this.checkLoginStatus, 2000);
这里改成 `this.checkLoginSetTimeoutID = setTimeout(this.checkLoginStatus, 2000);`
然后在 `componentWillUnmount` 里取消

2020-12-23 08:10 UTC, BlackHole1 commented on src/renderer-app/src/components/MainPageLayout.tsx
> +        this.userAvatar = localStorage.getItem("avatar") ?? '';
和上面的问题一样

2020-12-23 08:14 UTC, crimx requested changes

2020-12-23 08:14 UTC, crimx commented on src/renderer-app/src/IndexPage.tsx
> +        const token = localStorage.getItem("token");
这里的 token 最好用具体一些的名字。

2020-12-23 08:14 UTC, crimx commented on src/renderer-app/src/components/MainPageLayout.tsx
> +        this.userAvatar = localStorage.getItem("avatar") ?? '';
这里的 avatar 也应该用具体的名称，避免冲突。

2020-12-23 08:14 UTC, crimx commented on src/renderer-app/src/components/WeChatLogin.tsx
> +                    localStorage.setItem("userUUID", data.userUUID);
这里也是，参照 utils/localstorage/room 设定一层接口吧。

2020-12-24 02:15 UTC, BlackHole1 requested changes

2020-12-24 02:15 UTC, BlackHole1 commented on src/renderer-app/src/IndexPage.tsx
> +        console.log("token", token);
多余的 Console

2020-12-24 04:02 UTC, crimx approved these changes, later dismissed

2020-12-24 05:48 UTC, BlackHole1 approved these changes

2020-12-24 05:48 UTC, merged