feat(i18n): AppUpgradeModal、CloudStorageContainer
netless-io/flat pull request #742
Opened 2021-06-16 02:07 UTC by Leooeloel

2021-06-16 02:20 UTC, Cheerego7 commented on packages/flat-i18n/locales/zh-CN.json
> +  "end-series": "结束重复",
"end-repeat"

2021-06-16 02:20 UTC, Cheerego7 commented on packages/flat-i18n/locales/en.json
> +  "end-series": "End series",
"end-repeat": "End Repeat"

2021-06-16 04:26 UTC, BlackHole1 requested changes

2021-06-16 04:26 UTC, BlackHole1 commented on packages/flat-i18n/locales/zh-CN.json
> +  "new-version-tips": "发现新版本{{version}}, 请更新到最新版本获取更好的产品体验"
```suggestion
  "new-version-tips": "发现新版本: {{version}}, 请更新到最新版本获取更好的产品体验"
```

2021-06-16 04:26 UTC, BlackHole1 commented on packages/flat-i18n/locales/en.json
> +  "new-version-tips": "Found a new version {{version}}, please update to the latest version for a better product experience",
```suggestion
  "new-version-tips": "Found a new version: {{version}}, please update to the latest version for a better product experience",
```

2021-06-17 09:44 UTC, BlackHole1 approved these changes

2021-06-17 09:45 UTC, Cheerego7 approved these changes

2021-06-17 09:53 UTC, merged