feat(i18n): add CloudStoragePage
netless-io/flat pull request #758
Opened 2021-06-24 02:46 UTC by Leooeloel

2021-06-24 06:01 UTC, Cheerego7 approved these changes

2021-06-25 01:55 UTC, BlackHole1 requested changes

2021-06-25 01:55 UTC, BlackHole1 commented on desktop/renderer-app/package.json
> +    "i18next": "^20.3.1",
why upgrade `i18next`

2021-06-25 02:16 UTC, crimx commented on desktop/renderer-app/package.json
> +    "i18next": "^20.3.1",
统一了 i18next 版本

2021-06-25 02:36 UTC, BlackHole1 approved these changes

2021-06-25 02:36 UTC, merged