feat(i18n): add all tips
netless-io/flat pull request #765
Opened 2021-06-25 09:39 UTC by Leooeloel

2021-06-25 10:12 UTC, BlackHole1 requested changes

2021-06-25 10:12 UTC, BlackHole1 commented on desktop/main-app/src/bootup/Init-webRequest.ts
> +            }
remove

2021-06-25 10:49 UTC, crimx submitted a review, later dismissed

2021-06-25 11:00 UTC, BlackHole1 approved these changes, later dismissed

2021-06-27 09:20 UTC, BlackHole1 requested changes
CI warning:

<img width="1304" alt="图片" src="https://user-images.githubusercontent.com/8198408/123539346-e21dac00-d76b-11eb-8980-78f46daa18be.png">

https://github.com/netless-io/flat/pull/765/checks?check_run_id=2914492296#step:6:319

2021-06-28 03:03 UTC, Leooeloel commented
> CI warning:
> 
> <img alt="图片" width="1304" src="https://user-images.githubusercontent.com/8198408/123539346-e21dac00-d76b-11eb-8980-78f46daa18be.png">
> 
> https://github.com/netless-io/flat/pull/765/checks?check_run_id=2914492296#step:6:319

Resolved

2021-06-28 06:34 UTC, BlackHole1 approved these changes

2021-06-28 06:34 UTC, merged