feat(web): support share screen
netless-io/flat pull request #881
Opened 2021-08-19 08:27 UTC by BlackHole1

2021-08-19 08:28 UTC, hyrious submitted a review, later dismissed

2021-08-20 01:45 UTC, crimx requested changes

2021-08-20 01:45 UTC, crimx commented on web/flat-web/src/stores/ShareScreenStore/index.ts
> +                    this.listenerOtherUserShareScreen = new ListenerOtherUserShareScreen(
这里要不要销毁已有的 `this.listenerOtherUserShareScreen`

2021-08-20 01:50 UTC, BlackHole1 commented on web/flat-web/src/stores/ShareScreenStore/index.ts
> +                    this.listenerOtherUserShareScreen = new ListenerOtherUserShareScreen(
yes

2021-08-20 06:23 UTC, crimx approved these changes

2021-08-20 06:47 UTC, merged