feat(flat-components): add scenes controller components
netless-io/flat pull request #886
Opened 2021-08-23 09:51 UTC by Cheerego7

2021-08-23 15:37 UTC, BlackHole1 requested changes
less use namespace. eg:

```less
// good
.box {
    &.active {}
    
    &:hover {}
    
    .item {
        & > span > a {}
    }
}

// bad
.box {}

.box-active {}

.box:hover {}

.box-item {}

.box-item > span > a {}
```

2021-08-23 15:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +    currentScene: number;
currentSceneIndex

2021-08-23 15:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +    const isLastScene = currentScene + 1 === scenesCount;
isEndScene

2021-08-23 15:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/style.less
> +}
```suggestion
    &.disabled {
        opacity: 0.5;
        * {
            cursor: not-allowed;
        }
    }
}
```

2021-08-23 15:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +                "scenes-controller-container-disabled": disabled,
```suggestion
                disabled,
```

2021-08-23 15:37 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +                <div className="scenes-controller-btn" onClick={disabled ? undefined : addScene}>
```ts
const warpOnClick = useCallback(fn => {
    if (disabled) {
        return () => {};
    }
    
    return fn();
}, disabled);

onClick={warpOnClick(addScene)}
```

2021-08-24 01:43 UTC, Cheerego7 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +    const isLastScene = currentScene + 1 === scenesCount;
there is no ambiguity

2021-08-24 01:44 UTC, BlackHole1 commented on packages/flat-components/src/components/ClassroomPage/ScenesController/index.tsx
> +    const isLastScene = currentScene + 1 === scenesCount;
`First` and `End` match better

2021-08-24 02:26 UTC, BlackHole1 approved these changes

2021-08-24 02:26 UTC, merged