refactor(web): move some logic from avatar.ts to room.ts
netless-io/flat pull request #911
Opened 2021-09-02 08:46 UTC by hyrious

2021-09-02 09:02 UTC, Cheerego7 requested changes

2021-09-02 09:02 UTC, Cheerego7 commented on web/flat-web/src/apiMiddleware/rtc/testing.ts
> +export type {};
remove

2021-09-02 10:19 UTC, BlackHole1 submitted a review, later dismissed

2021-09-02 10:20 UTC, Cheerego7 approved these changes, later dismissed

2021-09-03 01:40 UTC, Cheerego7 approved these changes

2021-09-03 01:40 UTC, BlackHole1 approved these changes

2021-09-03 01:47 UTC, BlackHole1 commented
WIP

2021-09-03 03:31 UTC, merged