docs(readme): update readme and license
netless-io/flat pull request #927
Opened 2021-09-06 05:46 UTC by BlackHole1

- lint README(-zh).md
- update LICENSE
- add twitter and slack badge
- add related project
- add release version description

2021-09-06 09:04 UTC, crimx requested changes

2021-09-06 09:04 UTC, crimx commented on LICENSE
> +Copyright (c) 2020 Agora
2021

2021-09-07 05:45 UTC, Cheerego7 approved these changes

2021-09-07 05:54 UTC, crimx approved these changes

2021-09-07 05:57 UTC, merged

2026-08-16 22:17 UTC, arroselli commented on LICENSE
> +Copyright (c) 2020 Agora
- [ ]