Fix https://github.com/netless-io/flat/issues/804
netless-io/flat pull request #938
Opened 2021-09-08 10:30 UTC by yamasite

2021-09-08 10:41 UTC, BlackHole1 commented
close: https://github.com/netless-io/flat/issues/804

2021-09-09 04:44 UTC, BlackHole1 commented on desktop/main-app/webpack/webpack.common.js
> +        devtoolModuleFilenameTemplate:'file:///[absolute-resource-path]',
After a lot of testing, I found that this property does not play any role.

According to https://github.com/netless-io/flat/issues/804#issuecomment-915116112 I found another solution

We just need to change the devtools to `inline-source-map` in `desktop/main-app/webpack/webpack.commonjs`

e.g:
<img width="752" alt="图片" src="https://user-images.githubusercontent.com/8198408/132623931-e2a3c5a3-ec08-4351-98d1-310eea29a9cb.png">

2021-09-09 04:44 UTC, BlackHole1 requested changes

2021-09-09 04:44 UTC, BlackHole1 commented on desktop/main-app/webpack/webpack.common.js
> +        devtoolModuleFilenameTemplate:'file:///[absolute-resource-path]',
After a lot of testing, I found that this property does not play any role.

According to https://github.com/netless-io/flat/issues/804#issuecomment-915116112 I found another solution

We just need to change the devtools to `inline-source-map` in `desktop/main-app/webpack/webpack.commonjs`

e.g:
<img width="752" alt="图片" src="https://user-images.githubusercontent.com/8198408/132623931-e2a3c5a3-ec08-4351-98d1-310eea29a9cb.png">

2021-09-09 05:09 UTC, yamasite commented
Thanks for testing. In my Mac machine, if I comment it out:

![image](https://user-images.githubusercontent.com/10089260/132625864-63d669c2-31dd-4acc-8036-c8430b1f59ef.png)

The error recurs:

![image](https://user-images.githubusercontent.com/10089260/132625901-e6f74719-8450-4dc0-9084-77c550b0bb65.png)

If I remove the comment sign, the warnings go away:

![image](https://user-images.githubusercontent.com/10089260/132626012-a0c3c573-b90d-4633-a8b9-2f91379a4556.png)

Also, changing to `inline-source-map` does not remove the warning:

![image](https://user-images.githubusercontent.com/10089260/132626145-618ba92b-6a3f-41c9-a065-adedeb180d2a.png)

![image](https://user-images.githubusercontent.com/10089260/132626206-a65dc6ac-9537-42f0-9640-79721e5930cd.png)

Could you show your outcome for `inline-source-map`?

2021-09-09 05:35 UTC, BlackHole1 commented
When I use inline-source-map, my code looks like this:

<img width="1323" alt="图片" src="https://user-images.githubusercontent.com/8198408/132626967-c06d6894-2824-4ff0-a475-4448530892ed.png">


I suspect it is caused by your not rebuilding. Because after using `inline-source-map`, the code should be `//# sourceMappingURL=data:application/json;charset=utf-8;base64,xxxx` and not `/# sourceMappingURL=preload.js.map`

First make sure you make the same changes as in the picture below:

<img width="867" alt="图片" src="https://user-images.githubusercontent.com/8198408/132627281-bdc09b18-b5bf-4806-93e0-6c07da1b749e.png">


Then re-run `yarn run start`

This is the video I recorded:

https://user-images.githubusercontent.com/8198408/132628523-bda84cfd-0b29-4786-9541-5691873ce9bd.mp4

2021-09-09 05:43 UTC, yamasite commented
Tried again. Works as your video indicates: 

![image](https://user-images.githubusercontent.com/10089260/132629484-346e0147-aa2f-43c4-8cdd-d00c5e672325.png)

Thanks.

So `devtoolModuleFilenameTemplate` does not work for you?

2021-09-09 05:47 UTC, yamasite commented
Anyway, I think `inline-source-map` is a better approach. Have implemented the changes.

2021-09-09 06:00 UTC, BlackHole1 approved these changes

2021-09-09 06:06 UTC, merged

2021-09-09 06:07 UTC, BlackHole1 commented
Congrats on merging your first pull request! 🎉🎉🎉

2021-09-09 06:08 UTC, BlackHole1 commented
We will contact you via email in the next few days to send you a gift