feat(flat-components): add invite code support
netless-io/flat pull request #993
Opened 2021-10-12 13:27 UTC by Cheerego7

- add inviteCode in flatServers

2021-10-12 13:28 UTC, hyrious submitted a review, later dismissed

2021-10-13 01:24 UTC, BlackHole1 requested changes

2021-10-13 01:24 UTC, BlackHole1 commented on desktop/renderer-app/src/apiMiddleware/flatServer/index.ts
> +    /** 房间邀请码 */
to english

2021-10-13 01:24 UTC, BlackHole1 commented on desktop/renderer-app/src/pages/HomePage/MainRoomMenu/JoinRoomBox.tsx
> +            await sp(onJoinRoom(values.roomUUID.replace(/\s+/g, "")));
put the `replace` operation in `onJoinRoom`

2021-10-13 01:24 UTC, BlackHole1 commented on desktop/renderer-app/src/stores/RoomStore.ts
> +    /** 房间邀请码 */
to english

2021-10-13 01:24 UTC, BlackHole1 commented on packages/flat-components/src/components/InviteModal/index.tsx
> +
use css content

2021-10-13 01:24 UTC, BlackHole1 commented on packages/flat-components/src/components/RoomDetailPage/RoomDetailBody/index.tsx
> +
use content

2021-10-13 01:24 UTC, BlackHole1 commented on packages/flat-components/src/types/room.ts
> +    /** 房间邀请码 */
to english

2021-10-13 01:24 UTC, BlackHole1 commented on web/flat-web/src/apiMiddleware/flatServer/index.ts
> +    /** 房间邀请码 */
to english

2021-10-13 01:24 UTC, BlackHole1 commented on web/flat-web/src/pages/HomePage/MainRoomMenu/JoinRoomBox.tsx
> +            await sp(onJoinRoom(values.roomUUID.replaceAll(" ", "")));
put the `replace` operation in `onJoinRoom` to complete

2021-10-13 01:24 UTC, BlackHole1 commented on web/flat-web/src/stores/RoomStore.ts
> +    /** 房间邀请码 */
to english

2021-10-13 01:24 UTC, BlackHole1 commented on packages/flat-components/src/components/InviteModal/index.tsx
> +    if (inviteCode && /^\d{10}$/.test(inviteCode)) {
inviteCode definitely exists

2021-10-13 06:03 UTC, BlackHole1 requested changes

2021-10-13 06:03 UTC, BlackHole1 commented on packages/flat-components/src/utils/room.ts
> +};
```suggestion
export const formatInviteCode = (inviteCode: string, uuid: string): string => {
    if (/^\d{10}$/.test(inviteCode)) {
        // 123456789 -> 123 456 7890
        return inviteCode.slice(0, 3) + " " + inviteCode.slice(3, 6) + " " + inviteCode.slice(6);
    }
    return uuid;
};
```

2021-10-13 06:46 UTC, BlackHole1 approved these changes

2021-10-13 07:08 UTC, merged